### ISSUE TITLE
加载模型验证时有问题

### ISSUE THREAD

**Issue by jxy-001** [aespresso/a_journey_into_math_of_ml#5]
我用v2版本训练出模型后加载模型时说
RuntimeError: Error(s) in loading state_dict for Bert_Sentiment_Analysis:
	Unexpected key(s) in state_dict: "dense.weight", "dense.bias". 
请问是要改哪个地方呢？感谢

**Comment by JBoRu** [comment]
请问你解决了这个问题吗？  我也碰到了

**Comment by jxy-001** [comment]
我当时用pycharm直接跑有问题，但用jupyter一步步下来就没问题，而且注意训练和验证两个导入都要是v2版本的

**Comment by JBoRu** [comment]
感谢，原因就是训练和验证都要是v2版本的！

**Comment by jxy-001** [comment]
有时间也帮我解决一下我的问题呗，那个数据集清洗，感谢
